"""主体に人と機械の別を持たせる

Revision ID: 54c6d1626958
Revises: b0c8cc628c00
Create Date: 2026-08-28 21:46:42.241466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54c6d1626958'
down_revision: Union[str, Sequence[str], None] = 'b0c8cc628c00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        # 既存の主体はすべて機械（資格情報で名乗ってきたもの）。既定値を置いてから
        # NOT NULL にする。**人の主体は後から明示的に登録する。**
        batch_op.add_column(
            sa.Column(
                'subject_type', sa.String(length=16),
                nullable=False, server_default='machine',
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('subject_type')

    # ### end Alembic commands ###
