"""initial schema

Revision ID: 85063df8430e
Revises: 
Create Date: 2026-08-28 22:04:45.073090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85063df8430e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('authority', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('target', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.create_index('ix_audit_authority_at', ['authority', 'at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_event_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_event_client_id'), ['client_id'], unique=False)

    op.create_table('naan',
    sa.Column('naan', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_authoritative', sa.Boolean(), nullable=False),
    sa.Column('redirect', sa.String(length=500), nullable=False),
    sa.Column('na_policy', sa.String(length=500), nullable=False),
    sa.Column('minter', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(is_authoritative AND redirect = '') OR (NOT is_authoritative AND redirect <> '')", name='naan_redirect_only_when_not_authoritative'),
    sa.PrimaryKeyConstraint('naan')
    )
    op.create_table('manager',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('naan', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('default_shoulder_id', sa.Integer(), nullable=True),
    sa.Column('commitment_level', sa.String(length=32), nullable=False),
    sa.Column('quota_per_day', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('succeeded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['default_shoulder_id'], ['shoulder.id'], name='fk_manager_default_shoulder', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['naan'], ['naan.naan'], ),
    sa.ForeignKeyConstraint(['succeeded_by_id'], ['manager.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('naan', 'name', name='uniq_manager_name_per_naan')
    )
    with op.batch_alter_table('manager', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_manager_naan'), ['naan'], unique=False)

    op.create_table('shoulder',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shoulder', sa.String(length=50), nullable=False),
    sa.Column('naan', sa.String(length=10), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('redirect', sa.String(length=500), nullable=False),
    sa.Column('minter', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status <> 'delegated' OR minter <> ''", name='delegated_shoulder_needs_a_minter'),
    sa.ForeignKeyConstraint(['manager_id'], ['manager.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['naan'], ['naan.naan'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shoulder', 'naan', name='uniq_shoulder_per_naan')
    )
    with op.batch_alter_table('shoulder', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shoulder_manager_id'), ['manager_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shoulder_naan'), ['naan'], unique=False)
        batch_op.create_index(batch_op.f('ix_shoulder_status'), ['status'], unique=False)

    op.create_table('ark',
    sa.Column('ark', sa.String(length=200), nullable=False),
    sa.Column('naan', sa.String(length=10), nullable=False),
    sa.Column('shoulder_id', sa.Integer(), nullable=False),
    sa.Column('assigned_name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('commitment', sa.Text(), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('identifier', sa.Text(), nullable=False),
    sa.Column('format', sa.Text(), nullable=False),
    sa.Column('relation', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('who', sa.Text(), nullable=False),
    sa.Column('when', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['naan'], ['naan.naan'], ),
    sa.ForeignKeyConstraint(['shoulder_id'], ['shoulder.id'], ),
    sa.PrimaryKeyConstraint('ark')
    )
    with op.batch_alter_table('ark', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ark_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ark_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_ark_naan'), ['naan'], unique=False)
        batch_op.create_index('ix_ark_shoulder_created', ['shoulder_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ark_shoulder_id'), ['shoulder_id'], unique=False)

    op.create_table('client',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('naan', sa.String(length=10), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('subject_type', sa.String(length=16), nullable=False),
    sa.Column('authority', sa.String(length=16), nullable=False),
    sa.Column('shoulder_id', sa.Integer(), nullable=True),
    sa.Column('allowed_scopes', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['manager.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['naan'], ['naan.naan'], ),
    sa.ForeignKeyConstraint(['shoulder_id'], ['shoulder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_client_id'), ['client_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_client_manager_id'), ['manager_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_naan'), ['naan'], unique=False)
        batch_op.create_index('uniq_active_label_per_manager', ['manager_id', 'label'], unique=True, postgresql_where=sa.text('active IS true'), sqlite_where=sa.text('active IS true'))

    op.create_table('credential',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_pk', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('hashed', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_pk'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credential', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credential_client_pk'), ['client_pk'], unique=False)
        batch_op.create_index(batch_op.f('ix_credential_prefix'), ['prefix'], unique=False)

    op.create_table('mint_receipt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('request_id', sa.String(length=200), nullable=False),
    sa.Column('ark', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ark'], ['ark.ark'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'request_id', name='one_ark_per_request_id')
    )
    with op.batch_alter_table('mint_receipt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mint_receipt_client_id'), ['client_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mint_receipt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mint_receipt_client_id'))

    op.drop_table('mint_receipt')
    with op.batch_alter_table('credential', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credential_prefix'))
        batch_op.drop_index(batch_op.f('ix_credential_client_pk'))

    op.drop_table('credential')
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index('uniq_active_label_per_manager', postgresql_where=sa.text('active IS true'), sqlite_where=sa.text('active IS true'))
        batch_op.drop_index(batch_op.f('ix_client_naan'))
        batch_op.drop_index(batch_op.f('ix_client_manager_id'))
        batch_op.drop_index(batch_op.f('ix_client_client_id'))

    op.drop_table('client')
    with op.batch_alter_table('ark', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ark_shoulder_id'))
        batch_op.drop_index('ix_ark_shoulder_created')
        batch_op.drop_index(batch_op.f('ix_ark_naan'))
        batch_op.drop_index(batch_op.f('ix_ark_created_by'))
        batch_op.drop_index(batch_op.f('ix_ark_created_at'))

    op.drop_table('ark')
    with op.batch_alter_table('shoulder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shoulder_status'))
        batch_op.drop_index(batch_op.f('ix_shoulder_naan'))
        batch_op.drop_index(batch_op.f('ix_shoulder_manager_id'))

    op.drop_table('shoulder')
    with op.batch_alter_table('manager', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_manager_naan'))

    op.drop_table('manager')
    op.drop_table('naan')
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_event_client_id'))
        batch_op.drop_index(batch_op.f('ix_audit_event_at'))
        batch_op.drop_index('ix_audit_authority_at')

    op.drop_table('audit_event')
    # ### end Alembic commands ###
