# Generated by Django 5.2.17 on 2026-08-16 14:53

import django.db.models.deletion
import oauth2_provider.generators
import oauth2_provider.models
from django.conf import settings
from django.db import migrations, models

import jc2ark.ark.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("client_id", models.CharField(db_index=True, max_length=255)),
                ("authority", models.CharField(max_length=16)),
                ("action", models.CharField(max_length=32)),
                ("target", models.CharField(blank=True, default="", max_length=200)),
                ("detail", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["authority", "at"], name="ark_auditev_authori_1d43de_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Naan",
            fields=[
                ("naan", models.CharField(max_length=10, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("is_authoritative", models.BooleanField(default=True)),
                ("redirect", models.CharField(blank=True, default="", max_length=500)),
                ("na_policy", models.CharField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("is_authoritative", True), ("redirect", "")),
                            models.Q(
                                ("is_authoritative", False),
                                models.Q(("redirect", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="naan_redirect_only_when_not_authoritative",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "commitment_level",
                    models.CharField(
                        choices=[
                            ("not-guaranteed", "Not Guaranteed（検証系・開発系）"),
                            (
                                "permanent-dynamic",
                                "Permanent: Dynamic Content（機関テナントの既定）",
                            ),
                            ("permanent-stable", "Permanent: Stable Content"),
                            ("permanent-unchanging", "Permanent: Unchanging Content"),
                            ("descriptive-only", "記述のみ（物理オブジェクト。所在は変わりうる）"),
                        ],
                        default="permanent-dynamic",
                        max_length=32,
                    ),
                ),
                ("quota_per_day", models.PositiveIntegerField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "naan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="managers",
                        to="ark.naan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shoulder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "shoulder",
                    models.CharField(
                        max_length=50, validators=[jc2ark.ark.models._validate_shoulder]
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("redirect", models.CharField(blank=True, default="", max_length=500)),
                ("minter", models.URLField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shoulders",
                        to="ark.manager",
                    ),
                ),
                (
                    "naan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shoulders",
                        to="ark.naan",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="manager",
            name="default_shoulder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="ark.shoulder",
            ),
        ),
        migrations.CreateModel(
            name="Ark",
            fields=[
                (
                    "ark",
                    models.CharField(
                        editable=False, max_length=200, primary_key=True, serialize=False
                    ),
                ),
                ("assigned_name", models.CharField(editable=False, max_length=100)),
                ("url", models.URLField(blank=True, default="")),
                ("commitment", models.TextField(blank=True, default="")),
                ("metadata", models.TextField(blank=True, default="")),
                ("title", models.TextField(blank=True, default="")),
                ("type", models.TextField(blank=True, default="")),
                ("identifier", models.TextField(blank=True, default="")),
                ("format", models.TextField(blank=True, default="")),
                ("relation", models.TextField(blank=True, default="")),
                ("source", models.TextField(blank=True, default="")),
                ("who", models.TextField(blank=True, default="")),
                ("when", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.CharField(blank=True, db_index=True, default="", max_length=255),
                ),
                ("updated_by", models.CharField(blank=True, default="", max_length=255)),
                (
                    "naan",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="arks",
                        to="ark.naan",
                    ),
                ),
                (
                    "shoulder",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="arks",
                        to="ark.shoulder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.CharField(
                        db_index=True,
                        default=oauth2_provider.generators.generate_client_id,
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "redirect_uris",
                    models.TextField(blank=True, help_text="Allowed URIs list, space separated"),
                ),
                (
                    "post_logout_redirect_uris",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Allowed Post Logout URIs list, space separated",
                    ),
                ),
                (
                    "client_type",
                    models.CharField(
                        choices=[("confidential", "Confidential"), ("public", "Public")],
                        max_length=32,
                    ),
                ),
                (
                    "authorization_grant_type",
                    models.CharField(
                        choices=[
                            ("authorization-code", "Authorization code"),
                            ("urn:ietf:params:oauth:grant-type:device_code", "Device Code"),
                            ("implicit", "Implicit"),
                            ("password", "Resource owner password-based"),
                            ("client-credentials", "Client credentials"),
                            ("openid-hybrid", "OpenID connect hybrid"),
                        ],
                        max_length=44,
                    ),
                ),
                (
                    "client_secret",
                    oauth2_provider.models.ClientSecretField(
                        blank=True,
                        db_index=True,
                        default=oauth2_provider.generators.generate_client_secret,
                        help_text="Client secret for authentication",
                        max_length=255,
                    ),
                ),
                ("hash_client_secret", models.BooleanField(default=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("skip_authorization", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "algorithm",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "No OIDC support"),
                            ("RS256", "RSA with SHA-2 256"),
                            ("HS256", "HMAC with SHA-2 256"),
                        ],
                        default="",
                        max_length=5,
                    ),
                ),
                (
                    "allowed_origins",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Allowed origins list to enable CORS, space separated",
                    ),
                ),
                (
                    "registration_source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("dcr", "Dynamic Client Registration"),
                            ("cimd", "Client ID Metadata Document"),
                        ],
                        default="manual",
                        help_text="How this application was registered (manual, DCR per RFC 7591, or CIMD)",
                        max_length=32,
                    ),
                ),
                (
                    "cimd_expires_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="When the cached Client ID Metadata Document should be re-fetched",
                        null=True,
                    ),
                ),
                (
                    "authority",
                    models.CharField(
                        choices=[
                            ("manager", "その manager の shoulder のみ"),
                            ("naan", "NAAN 配下の全 shoulder（break-glass。平時は発行しない）"),
                        ],
                        default="manager",
                        max_length=16,
                    ),
                ),
                ("allowed_scopes", models.CharField(default="ark:mint", max_length=200)),
                ("active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("label", models.CharField(blank=True, default="", max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients",
                        to="ark.manager",
                    ),
                ),
                (
                    "naan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clients",
                        to="ark.naan",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("active", True)),
                        fields=("manager", "label"),
                        name="uniq_active_label_per_manager",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="shoulder",
            constraint=models.UniqueConstraint(
                fields=("shoulder", "naan"), name="uniq_shoulder_per_naan"
            ),
        ),
        migrations.AddConstraint(
            model_name="manager",
            constraint=models.UniqueConstraint(
                fields=("naan", "name"), name="uniq_manager_name_per_naan"
            ),
        ),
        migrations.AddIndex(
            model_name="ark",
            index=models.Index(
                fields=["shoulder", "created_at"], name="ark_ark_shoulde_6188cc_idx"
            ),
        ),
    ]
