# Generated by Django 5.2.17 on 2026-08-16 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ark", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="shoulder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clients",
                to="ark.shoulder",
            ),
        ),
    ]
