# Generated by Django 5.2.17 on 2026-08-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ark", "0002_client_shoulder"),
    ]

    operations = [
        migrations.AddField(
            model_name="naan",
            name="minter",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="shoulder",
            name="note",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="shoulder",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "採番できる"),
                    ("reserved", "**リザーブ枠。** 名前空間を押さえてあるだけで採番できない"),
                    ("delegated", "**採番は外部 minter。** ここでは受けず案内する"),
                    ("retired", "新規採番はしない。**既存 ARK は解決し続ける**（NR）"),
                ],
                db_index=True,
                default="active",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="shoulder",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "delegated"), _negated=True),
                    models.Q(("minter", ""), _negated=True),
                    _connector="OR",
                ),
                name="delegated_shoulder_needs_a_minter",
            ),
        ),
    ]
