# Generated by Django 5.2.17 on 2026-08-17 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ark", "0003_naan_minter_shoulder_note_shoulder_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="manager",
            name="succeeded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="predecessors",
                to="ark.manager",
            ),
        ),
    ]
