# Generated by Django 5.2.17 on 2026-08-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ark', '0004_manager_succeeded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='authority',
            field=models.CharField(choices=[('manager', 'その機関の shoulder のみ'), ('naan', 'NAAN 配下の全 shoulder（break-glass）')], default='manager', max_length=16),
        ),
        migrations.AlterField(
            model_name='manager',
            name='commitment_level',
            field=models.CharField(choices=[('not-guaranteed', '保証なし（検証・開発系）'), ('permanent-dynamic', '恒久・内容は更新されうる（既定）'), ('permanent-stable', '恒久・内容は実質不変'), ('permanent-unchanging', '恒久・内容は一切不変'), ('descriptive-only', '記述のみ（所在は変わりうる）')], default='permanent-dynamic', max_length=32),
        ),
        migrations.AlterField(
            model_name='shoulder',
            name='status',
            field=models.CharField(choices=[('active', '採番できる'), ('reserved', 'リザーブ枠（採番できない）'), ('delegated', '採番は外部 minter（案内する）'), ('retired', '新規採番なし（既存は解決し続ける）')], db_index=True, default='active', max_length=16),
        ),
    ]
