# Generated by Django 5.2.17 on 2026-08-18 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ark", "0005_alter_client_authority_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MintReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("client_id", models.CharField(db_index=True, max_length=255)),
                ("request_id", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ark",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipts",
                        to="ark.ark",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("client_id", "request_id"), name="one_ark_per_request_id"
                    )
                ],
            },
        ),
    ]
